---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 1m
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  values:
    server:
      extraFlags:
        - web.enable-remote-write-receiver

      persistentVolume:
        enabled: false

      service:
        servicePort: 9090

    serverFiles:
      prometheus.yml:
        scrape_configs: []

    configmapReload:
      prometheus:
        enabled: false

    alertmanager:
      enabled: false

    kube-state-metrics:
      enabled: false

    prometheus-node-exporter:
      enabled: false

    prometheus-pushgateway:
      enabled: false
