---
version: 2
updates:
  - package-ecosystem: docker
    directory: /charts/query-test/container
    schedule:
      interval: daily
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /tools/schema-generator
    schedule:
      interval: daily
    labels:
      - dependencies
      - docker
