---
tests:
  - env:
      CLUSTER: pod-logs-feature-test
      LOKI_URL: http://loki.loki.svc:3100/loki/api/v1/query
      LOKI_TENANTID: 1
      LOKI_USER: loki
      LOKI_PASS: lokipassword

    queries:
      # Gets Pod logs based on default job label
      # Also ensure that we are getting pods from Nodes with taints
      - query: count_over_time({cluster="$CLUSTER", job="production/busybox", namespace="production"}[1h])
        type: logql

      # Gets Pod logs based on annotation job label
      - query: count_over_time({cluster="$CLUSTER", job="dev-pod", namespace="development"}[1h])
        type: logql
