---
# -- Name override
# @section -- General settings
nameOverride: ""

# -- Full name override
# @section -- General settings
fullnameOverride: ""

# -- The checks to run.
# @section -- Test settings
checks: []

# -- Initial delay, in seconds, before starting the first test run.
# @section -- Test settings
initialDelay: 0

# -- Number of times to retry the test on failure.
# @section -- Test settings
attempts: 10

# -- Delay, in seconds, between test runs.
# @section -- Test settings
delay: 30

pod:
  # -- nodeSelector to apply to the test runner pod.
  # @section -- Job settings
  nodeSelector:
    kubernetes.io/os: linux

  # -- Extra annotations to add to the test runner pod.
  # @section -- Job settings
  extraAnnotations: {}

  # -- Extra labels to add to the test runner pod.
  # @section -- Job settings
  extraLabels: {}
  
  # -- Extra environment variables to add to the test runner pod.
  # @section -- Job settings
  extraEnv: {}

  # -- Tolerations to apply to the test runner pod.
  # @section -- Job settings
  tolerations: []

  # -- Service Account to use for the test runner pod.
  # @section -- Job settings
  serviceAccount:
    create: true

    name: ""

  # -- RBAC settings for the service account.
  # @section -- Job settings
  rbac:
    create: true

image:
  # -- Test pod image registry.
  # @section -- Image settings
  registry: ghcr.io
  # -- Test pod image repository.
  # @section -- Image settings
  repository: grafana/helm-chart-toolbox-kubernetes-objects-test
  # -- Test pod image tag. Default is the chart version.
  # @section -- Image settings
  tag: ""
  # -- Optional set of image pull secrets.
  # @section -- Image settings
  pullSecrets: []

## Global properties for overriding the image registry and pull secrets.
global:
  image:
    # -- Global image registry to use if it needs to be overridden for some specific use cases (e.g local registries, custom images, ...)
    # @section -- Image Registry
    registry: ""

    # -- Optional set of global image pull secrets.
    # @section -- Image Registry
    pullSecrets: []
