---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pyroscope
  namespace: pyroscope
spec:
  interval: 1m
  chart:
    spec:
      chart: pyroscope
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  values:
    alloy:
      enabled: false
