---
name: Lint
# yamllint disable-line rule:truthy
on:
  push:
    branches: ["main"]

  pull_request:

  workflow_dispatch:

permissions: {}

jobs:
  shellcheck:
    name: Shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: 'false'
      - name: Lint shell files
        run: make lint-shell

  yamllint:
    name: YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: 'false'
      - name: Lint YAML files
        run: make lint-yaml

  actionlint:
    name: GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: 'false'
      - uses: raven-actions/actionlint@01fce4f43a270a612932cb1c64d40505a029f821  # v2.0.0
