---
name: Test Helm Test

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
    paths: [tools/helm-test/**]
  pull_request:
    paths: [tools/helm-test/**]
  workflow_dispatch:

permissions: {}

jobs:
  list-tests:
    name: List tests
    runs-on: ubuntu-latest
    outputs:
      localTests: ${{ steps.list_tests.outputs.localTests }}
      cloudTests: ${{ steps.list_tests.outputs.cloudTests }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: 'false'

      - name: List tests
        id: list_tests
        working-directory: tools/helm-test/tests
        run: |
          localTests=()
          cloudTests=()
          for testPlan in */test-plan.yaml; do
            clusterType="$(yq '.cluster.type' "${testPlan}")"
            if [[ "${clusterType}" == "kind" ]] || [[ "${clusterType}" == "minikube" ]]; then
              localTests+=("$(dirname "${testPlan}")")
            else
              cloudTests+=("$(dirname "${testPlan}")")
            fi
          done
          echo "localTests=$(printf '%s\n' "${localTests[@]}" | jq --raw-input | jq --slurp --compact-output)" >> "${GITHUB_OUTPUT}"
          echo "cloudTests=$(printf '%s\n' "${cloudTests[@]}" | jq --raw-input | jq --slurp --compact-output)" >> "${GITHUB_OUTPUT}"

  run-integration-tests:
    name: Integration Test
    needs: list-tests
    runs-on: ubuntu-latest
    if: needs.list-tests.outputs.localTests != '[]'
    strategy:
      matrix:
        test: ${{ fromJson(needs.list-tests.outputs.localTests) }}
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: 'false'
          path: source

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: 'false'
          repository: grafana/hackathon-13-helm-chart-toolbox
          path: helm-chart-toolbox

      - name: Install Flux CLI
        uses: fluxcd/flux2/action@6bf37f6a560fd84982d67f853162e4b3c2235edb  # v2.6.4

      - name: Install Kind CLI
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3  # v1.12.0
        with:
          install_only: true

      - name: Install Minikube CLI
        uses: medyagh/setup-minikube@cea33675329b799adccc9526aa5daccc26cd5052  # v0.0.19
        with:
          start: false

      - name: Run test
        run: helm-chart-toolbox/tools/helm-test/helm-test "${TEST_DIRECTORY}"
        env:
          TEST_DIRECTORY: "source/tools/helm-test/tests/${{ matrix.test }}"
          DELETE_CLUSTER: true
