---
name: Test Doc Generator

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
    paths: [tools/doc-generator/**]
  pull_request:
    paths: [tools/doc-generator/**]
  workflow_dispatch:

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: 'false'

      - name: Run tests
        working-directory: tools/doc-generator
        run: make test
